GEMINI_API_KEY: 'AIzaSyCIoJroIWY9szjPTWna1RYLET1KwEKPhpM'
GOOGLE_API_KEY: 'AIzaSyCIoJroIWY9szjPTWna1RYLET1KwEKPhpM'
GOOGLE_CSE_ID: 'f0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e'
SUPABASE_API: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhbG5kZ2ZiYnRuYmNjcXJjYXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTQ3MTgsImV4cCI6MjA1NzczMDcxOH0.sj7fMwpRvBqrPT1w3jCyeil2oZBDWc-BCxZ3edWlD7M'