GEMINI_API_KEY: 'AIzaSyCIoJroIWY9szjPTWna1RYLET1KwEKPhpM'
GOOGLE_API_KEY: 'AIzaSyCIoJroIWY9szjPTWna1RYLET1KwEKPhpM'
GOOGLE_CSE_ID: 'f0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e'
SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhbG5kZ2ZiYnRuYmNjcXJjYXJhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjE1NDcxOCwiZXhwIjoyMDU3NzMwNzE4fQ.JK28oP1afHw_bhGp8NaFpgErQXmxfx5SugUlcC1FJLU'
SUPABASE_URL: 'https://ialndgfbbtnbccqrcara.supabase.co'